<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConstructorSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('constructors')->insert([
            [
                'ConstructorID' => 1,
                'Name' => 'Red Bull Racing',
                'Nationality' => 'Austria',
                'FoundedYear' => 2005,
                'TeamPrincipal' => 'Christian Horner',
                'Wins' => 123,
                'PolePositions' => 104,
                'Podiums' => 285,
                'WorldChampionships' => 6,
                'History' => '',
                'Image' => '',
            ],
            [
                'ConstructorID' => 2,
                'Name' => 'Scuderia Ferrari',
                'Nationality' => 'Italy',
                'FoundedYear' => 1950,
                'TeamPrincipal' => 'Frédéric Vasseur',
                'Wins' => 246,
                'PolePositions' => 252,
                'Podiums' => 811,
                'WorldChampionships' => 16,
                'History' => '',
                'Image' => '',
            ],
            [
                'ConstructorID' => 3,
                'Name' => 'Mercedes-AMG Petronas',
                'Nationality' => 'Germany',
                'FoundedYear' => 1954,
                'TeamPrincipal' => 'Toto Wolff',
                'Wins' => 125,
                'PolePositions' => 138,
                'Podiums' => 302,
                'WorldChampionships' => 8,
                'History' => '',
                'Image' => '',
            ],
            [
                'ConstructorID' => 4,
                'Name' => 'McLaren',
                'Nationality' => 'United Kingdom',
                'FoundedYear' => 1966,
                'TeamPrincipal' => 'Andrea Stella',
                'Wins' => 188,
                'PolePositions' => 158,
                'Podiums' => 522,
                'WorldChampionships' => 8,
                'History' => '',
                'Image' => '',
            ],
            [
                'ConstructorID' => 5,
                'Name' => 'Aston Martin Aramco',
                'Nationality' => 'United Kingdom',
                'FoundedYear' => 2021,
                'TeamPrincipal' => 'Mike Krack',
                'Wins' => 1,
                'PolePositions' => 1,
                'Podiums' => 17,
                'WorldChampionships' => 0,
                'History' => '',
                'Image' => '',
            ],
            [
                'ConstructorID' => 6,
                'Name' => 'BWT Alpine F1 Team',
                'Nationality' => 'France',
                'FoundedYear' => 1977,
                'TeamPrincipal' => 'Oliver Oakes',
                'Wins' => 1,
                'PolePositions' => 3,
                'Podiums' => 5,
                'WorldChampionships' => 0,
                'History' => '',
                'Image' => '',
            ],
            [
                'ConstructorID' => 7,
                'Name' => 'Williams Racing',
                'Nationality' => 'United Kingdom',
                'FoundedYear' => 1977,
                'TeamPrincipal' => 'James Vowles',
                'Wins' => 114,
                'PolePositions' => 128,
                'Podiums' => 313,
                'WorldChampionships' => 9,
                'History' => '',
                'Image' => '',
            ],
            [
                'ConstructorID' => 8,
                'Name' => 'Visa Cash App RB',
                'Nationality' => 'Italy',
                'FoundedYear' => 2006,
                'TeamPrincipal' => 'Laurent Mekies',
                'Wins' => 2,
                'PolePositions' => 1,
                'Podiums' => 7,
                'WorldChampionships' => 0,
                'History' => '',
                'Image' => '',
            ],
            [
                'ConstructorID' => 9,
                'Name' => 'Kick Sauber',
                'Nationality' => 'Switzerland',
                'FoundedYear' => 1993,
                'TeamPrincipal' => 'Alessandro Alunni Bravi',
                'Wins' => 1,
                'PolePositions' => 1,
                'Podiums' => 26,
                'WorldChampionships' => 0,
                'History' => '',
                'Image' => '',
            ],
            [
                'ConstructorID' => 10,
                'Name' => 'MoneyGram Haas F1 Team',
                'Nationality' => 'United States',
                'FoundedYear' => 2016,
                'TeamPrincipal' => 'Ayao Komatsu',
                'Wins' => 0,
                'PolePositions' => 1,
                'Podiums' => 0,
                'WorldChampionships' => 0,
                'History' => '',
                'Image' => '',
            ],
        ]);
    }
}